### PR TITLE
Bot.py: expose upstream send_aggressively option

### PR DESCRIPTION
**Pull request by tripleee**
This allows a bot to say it wants to merge adjacent messages which are pending for the same room, so it can post more quickly than one line per second.

Currently requires ChatExchenge from source again (my PR was just merged)

### CODE REVIEW

**Comment by double-fault** [comment]
@tripleee I've granted you write access for this repo. Do you have a PyPi account, and if so, what is your username? I'll add you as a maintainer for the package, and then you can make your own releases.

**Comment by tripleee** [comment]
Wow, thanks! I created the PR also to get a review, of course. I don't have a PYPI account but I'll go ahead and create one.

**Comment by double-fault** [comment]
@tripleee The commit looked good to me, and my computer is facing weird git issues which make testing somewhat hard. I'm currently downloading the repo and making a release. I'll let you know when I've made it.

**Comment by tripleee** [comment]
https://pypi.org/user/tripleee/

**Comment by double-fault** [comment]
@tripleee I've added you as a maintainer for the package on PyPi! If you face any issues, please ping me in SE chat. As always, if you aren't sure about a commit, make a PR and I'll review it.

**Comment by double-fault** [comment]
Oh, and I also just pushed version 0.7.5 to PyPi.

**Comment by tripleee** [comment]
Many thanks! I'll probably need to familiarize myself before I'm ready to actually publish a release but I'll start studying (-:

**Pull request merged**
