### PR TITLE
Release 0.7.5

### PR DESCRIPTION
**Pull request by tripleee**
Add version to README.md

### CODE REVIEW

**Comment by tripleee** [comment]
Didn'r realize I had to accept the project invitation separately so I didn't actually had the privileges to commit ... now I do, sorry for the noise! (-:

**Comment by fortunate-man** [comment]
Uhh... didn't version 0.7.5 already exist?

**Comment by tripleee** [comment]
Yeah, sorry, don't know exactly what happened here... I tried to edit directly on Github - maybe I had forgotten to refresh the page and then I missed that 0.7.5 was already there because the entries were in the wrong order. Maybe. Or something. I was confused; apologies for the disturbance.

**Comment by double-fault** [comment]
Yeah, no problem. I realized that when I saw the commit message, and I deleted my comment instantly. Guess I was ninja'd :D

**Comment by double-fault** [comment]
Also, the wrong order was due to a messy merge I performed; sorry 'bout that.

**Pull request merged**
